CREATE TABLE T_GMCAP_001_NEW_CLIENT
(
NEW_CLIENT_ID INT unsigned NOT NULL AUTO_INCREMENT,
CLIENT_NAME VARCHAR(50),
CLIENT_LAST_NAME VARCHAR(70),
CLIENT_ADDRESS VARCHAR(70),
CLIENT_FOLIO_ID VARCHAR(20),
ACCOUNT_AMOUNT NUMERIC(10,2),
ACCOUNT_START_DATE DATE,
PRIMARY KEY (NEW_CLIENT_ID)
);